# -*- coding: utf-8 -*-
"""Copy of Untitled_get_trans1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eNbyKDa58G43y4OWmlGJXR2QBLRi3Yhx
"""

#imported libraries
import pandas as pd
import numpy as np
import json
import csv

df = pd.read_csv("freecodecamp org id T.csv")
# output the dataframe
print(df)

!pip install youtube_transcript_api

col_list =  list(df["id"])

print(col_list)

chunk = np.array_split(np.array(col_list), 80) 
chu = chunk[0]
chunk_list = chu.tolist()

chunk_list

transcription = {}
for i in chunk_list:
    from youtube_transcript_api import YouTubeTranscriptApi
    try:
      srt = YouTubeTranscriptApi.get_transcript(i)  
      transcription[i] = srt     
    except:
      continue

transcription

type(transcription)

# Serializing json
json_object = json.dumps(transcription, indent=2)
# Writing to sample.json
with open("sample.json", "w") as outfile:
   outfile.write(json_object)